services:
# front
    next:
        build: ./next
        volumes:
        - ../app/front:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 3000:3000
        stdin_open: true
        depends_on:
            - "express"
        command: bash -c "npm i -g npm && npm install && npm run dev"
# back
    express:
        build: ./express
        volumes:
        - ../app/back:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 4000:3000
        depends_on:
            - "mysql"
            - "redis"
        command: bash -c "npm i -g npm && npm install && npm start"

    redis:
        build: ./redis
        ports: 
            - 6379:6379
    mysql:
        build: ./mysql
        ports:
        - 3306:3306